added templates for input field
RajnovicTeodora/DomainSpecificLanguagesProject pull request #31
Opened 2023-03-16 09:20 UTC by rajtarovN

#5

2023-03-19 12:36 UTC, RajnovicTeodora approved these changes

2023-03-19 13:13 UTC, oljamirilovic requested changes
Move to generator/templates directory and delete dsl_project directory

2023-03-20 21:11 UTC, oljamirilovic approved these changes

2023-03-20 21:19 UTC, rajtarovN commented
/Closes #5

2023-03-20 21:19 UTC, merged